---
- name: Prepare container instances
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Install prerequistes
      ansible.builtin.dnf:
        name: python3-dnf
        state: present
  
    - name: Install required packages
      ansible.builtin.dnf:
        name: "{{ required_packages }}"
        state: present
      when: required_packages is defined