---
- name: Update web servers
  hosts: webservers
  become: true

  tasks:
    - name: Ensure apache is at the present version
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Write the landing page
      ansible.builtin.copy:
        content: |
          <h1>Hello World!</h1>
        dest: /var/www/html/index.html
        mode: "0644"

- name: Update db servers
  hosts: databases
  become: true

  tasks:
    - name: Ensure postgresql is at the present version
      ansible.builtin.dnf:
        name: postgresql
        state: present
